### PR TITLE
Add image and some new badges to README

### PR DESCRIPTION
**Pull request by FrostyTheSouthernSnowman**
I copied over some images and badges from the README for SurrealDB in to the README for the python driver and reformatted the badges. Feel free to tell me if I should remove some of the badges for the pull request to get merged.

### CODE REVIEW

**Comment by FrostyTheSouthernSnowman** [comment]
This PR relates to issue #27

**Review by CaedenPH — APPROVED** [review]
Looks good

**Review by tsunyoku — APPROVED** [review]

**Comment by tsunyoku** [comment]
@FrostyTheSouthernSnowman I want to get this merged, but you PR'd from your main branch and now https://github.com/surrealdb/surrealdb.py/pull/28/commits/52634adc4ae945170a6de87ea8ce972e0225ab69 is included in the PR when not intended.. If you can rectify this, I'll get it merged.

**Comment by FrostyTheSouthernSnowman** [comment]
> @FrostyTheSouthernSnowman I want to get this merged, but you PR'd from your main branch and now [52634ad](https://github.com/surrealdb/surrealdb.py/commit/52634adc4ae945170a6de87ea8ce972e0225ab69) is included in the PR when not intended.. If you can rectify this, I'll get it merged.

Sorry about that, I will get it fixed as soon as possible.

**Comment by FrostyTheSouthernSnowman** [comment]
I have no idea how that got there, must have been for another idea I was working on. So sorry!

**Comment by FrostyTheSouthernSnowman** [comment]
I think I fixed it now. Sorry about that.

**Comment by tsunyoku** [comment]
> I think I fixed it now. Sorry about that.

Thanks!

**Pull request merged**
