### PR TITLE
Fix unhandled `KeyError`

### LINKED ISSUE #29: KeyError not handled in `http.py`
The line [`surreal_data = surreal_json[0]`](https://github.com/surrealdb/surrealdb.py/blob/f3550eed0bfe82c1af1a8fcc64c203b634f53596/surrealdb/clients/http.py#L118) in the `http.py` client introduces a behavior which cannot be handled by the end user. The majority of errors are `KeyError` errors and are completely unhanded (the else case is skipped).

 There needs to be an additional exception in the following manner which also gives more info for debugging:
```python
try:
    surreal_json: List[Dict[str, Any]] = jsonlib.loads(surreal_raw_data)
    print(surreal_json)
    surreal_data = surreal_json[0]
except JSONDecodeError:
    raise SurrealException(
        f"Invalid JSON response from SurrealDB: {surreal_raw_data}",
    )
except KeyError:
    raise SurrealException(
        "Query failed with status code "
        + f"{surreal_response.status_code}"
        + f"\ndetails: {surreal_json['details']}"
        + f"\ninformation: {surreal_json['information']}"
        + f"\ndescription: {surreal_json['description']}",
    )
```

### PR DESCRIPTION
**Pull request by TudorAndrei**
Fix #29

### CODE REVIEW

**Review by tsunyoku — COMMENTED** [review]
Hello, thanks for the PR! As for addressing the reasons in the issue for this change, I agree logging should be better. However, the reason it was the left the way it was is due to the fact I was unaware of how errors are sent by surreal on the API as there is generally a lack of documentation surrounding the REST API. Is this structure you're using in the exception persistent? If so, I'd prefer to JSON load into a model and use it that way. Also unsure on the formatting of the exception itself.

**Comment by TudorAndrei** [comment]
Regarding the formatting, i have chose to be as precise as I can since some relevant information is sometimes found in the `information` and sometimes in the `description`. Since the status code can be accessed, more detailed errors can be generated.

From my testing this structure handled most of my issues and provided enough information. It must be mentioned that, for now I have only used the `HTTPClient` in writing tests.

**Comment by kreczko** [comment]
The current patch creates an error message of the form
```
Traceback (most recent call last):
  File "/software/miniconda/envs/dice/lib/python3.8/site-packages/surrealdb/clients/http.py", line 118, in _request
    surreal_data = surreal_json[0]
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "surrealdb_example.py", line 117, in <module>
    asyncio.run(run_all())
  File "/software/miniconda/envs/dice/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/software/miniconda/envs/dice/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "surrealdb_example.py", line 106, in run_all
    await create_all()
  File "surrealdb_example.py", line 34, in create_all
    response = await client.create_all(table, data)
  File "/software/miniconda/envs/dice/lib/python3.8/site-packages/surrealdb/clients/http.py", line 178, in create_all
    response = await self._request(
  File "/software/miniconda/envs/dice/lib/python3.8/site-packages/surrealdb/clients/http.py", line 124, in _request
    raise SurrealException(
surrealdb.common.exceptions.SurrealException: Query failed with status code 403
details: Authentication failed
information: There was a problem with authentication
description: Your authentication details are invalid. Reauthenticate using valid authentication parameters.
```

Wouldn't it be more prudent to use exception chaining instead?
```python
        except KeyError as e:
            raise SurrealException(
                "Query failed with status code "
                + f"{surreal_response.status_code}"
                + f"\ndetails: {surreal_json['details']}"
                + f"\ninformation: {surreal_json['information']}"
                + f"\ndescription: {surreal_json['description']}",
            ) from e
```
This gives you
```
The above exception was the direct cause of the following exception:
```
instead of
```
During handling of the above exception, another exception occurred:
```

**Comment by TudorAndrei** [comment]
Thank you for the feedback. I have never handled or written many exceptions, so this is very useful. I will make the appropriate changes.

**Review by tsunyoku — APPROVED** [review]

**Pull request merged**
