### PR TITLE
Upgrade to Pydantic V2

### PR DESCRIPTION
**Pull request by M1N0RM1N3R**
Thank you for submitting this pull request! We appreciate you spending the time to work on these changes.

## What is the motivation?

Two words: dependency hell.  
I'm using Pydantic V2's features as part of a project, and updating wasn't particularly difficult--just change `allow_mutation = False` to `frozen = True`, bump the version number, and Bob's your uncle.

## Type of Change

- [x] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## What is your testing strategy?

I ran the updated version, as part of my project, locally. No major issues cropped up.

## Have you read the [Contributing Guidelines]?

- [x] I have read the [Contributing Guidelines]

[Contributing Guidelines]: https://github.com/surrealdb/surrealdb/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by AlexFrid** [comment]
Thanks for the PR 🙌 

We are currently putting a lot of effort into the next version of the Python library, which will be based on Rust, you can check it out here: https://pypi.org/project/surrealdb-beta/

That being said, this seems relatively simple, I'll test this out soon and then merge if there are no issues.

**Comment by alesauce** [comment]
Hi there! Is there any movement on merging this PR or releasing the next version of the Python library? This is currently a blocking issue for using the Python SDK for any clients that want to use Pydantic v2. Would appreciate any additional info, and am happy to help get it merged!

**Comment by TudorAndrei-Pythia** [comment]
@alesauce you can use this fork in the meantime

**Comment by treykeown** [comment]
Hey folks, unfortunately this is a pretty significant blocker - Pydantic V2 has been rolled out for a while now, and many other popular libraries (FastAPI) require it.

**Review by AlexFrid — APPROVED** [review]
Apologies for the delay on this 🙏

**Comment by M1N0RM1N3R** [comment]
> Apologies for the delay on this 🙏

No prob. I get that y'all have lives outside of maintaining this amazing DBMS and ecosystem, and that you may need to do much more rigorous testing to make sure there are no regressions. Besides the acceptance being on the slow side, I'd say that I'm satisfied with my first real contribution to an open-source project.

This is why I love open-source. It doesn't just let you know exactly what's running on your system, it doesn't just let you get more eyes on your own code, but it also lets you get your hands dirty and solve problems together, not just as a corporation, but as a community.

-- ⛏🦑

**Pull request merged**
